### ISSUE TITLE
open the include/insert file when using 'goto declaration'

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#12]
The go to declaration works now. But is it possible to jump to functions that were only included by _#include_ or _#insert_?
Additionally it would be good if the filename in the _#include/#insert_ line is clicked with the right mouse button to give you an option to open the file.

Sometimes my include files are not in the project directory.

**Comment by gosukiwi** [comment]
> The go to declaration works now. But is it possible to jump to functions that were only included by #include or #insert?

I haven't implemented `#insert` in the autocomplete yet (it should be a trivial change I'll probably address later) but _Go To Definition_ works for included files :)

> Additionally it would be good if the filename in the #include/#insert line is clicked with the right mouse button to give you an option to open the file.

That would be nice, particularly useful for files outside of the project. When inside I'd just prefer using `ctrl-p` and fuzzy-find the file there.

**Comment by gosukiwi** [comment]
You can now press F3 to go to any include (even outside project) :) 

Note that this won't work for files outside of the project (it works for files inside the project when they reference files outside, but not for files outside referencing any other file). 

This is because the way AGK manages includes, using all locations as relative to the current project.
