### ISSUE TITLE
Partial highlighting of variables or constants.

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#3]
If i have variables or constants with a key word in his name it will be highlightet.

Example
```
#constant KEY_LEFT         37
 moveleft as integer
```

**Comment by gosukiwi** [comment]
Uhm, the thing about this is that, at the moment, the highlight engine uses regular expressions in the form of TextMate grammars.

Because I don't do a full language parse, I don't know the name of the variables/constants defined, I have no context. 

One thing I thought about doing is that, if the identifier is `ALL_UPPERCASE` I can just highlight it as constant. I think it's a decent default, although it's not perfect of course.

**Comment by MadBit010** [comment]
The solution with `ALL_UPPERCASE ` would not bother me. But I don't think most people would like it that way.

**Comment by gosukiwi** [comment]
Yeah. I think the issue with that is that a) Tier 1 is case insensitive and doesn't enforce using all caps for constants, and b) most AGK users are new to programming and don't know about conding standards. So for them, all caps mean nothing.

**Comment by MadBit010** [comment]
You got that right.

But back to the actual issue.
Here is a small screenshot. Don't you think you can filter that out with TextMate? 

![grafik](https://user-images.githubusercontent.com/37149309/84980256-ddbebc00-b131-11ea-9fab-8cfe871a9cb9.png)

**Comment by gosukiwi** [comment]
Thanks for the report @MadBit010 , I didn't quite understand before. I just pushed a fix. It will come with version `0.3.2` later today :)
